# PostgreSQL. Versions 9.3 and up are supported.
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: nicolle123
  host: localhost
  port: 5432

development:
  <<: *default
  database: catalogo_filmes_development

test:
  <<: *default
  database: catalogo_filmes_test

production:
  <<: *default
  database: catalogo_filmes_production
  username: catalogo_filmes
  password: <%= ENV["CATALOGO_FILMES_DATABASE_PASSWORD"] %>